
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fil-rouge-prod
nameSuffix: -prod

resources:
  - ../../base
  - pdb.yaml

labels:
  - includeSelectors: false
    pairs:
      env: prod

replicas:
  - name: notes-api
    count: 3
  - name: notes-web
    count: 2

images:
  - name: localhost:5001/notes-api
    newTag: "2.0.0"

configMapGenerator:
  - name: notes-config
    behavior: merge
    literals:
      - APP_GREETING=PRODUCTION
      - APP_COLOR=#c53030

patches:
  - path: ressources-patch.yaml
    target:
      kind: Deployment
      name: notes-api
  - target:
      kind: Ingress
      name: notes
    patch: |-
      - op: replace
        path: /spec/rules/0/host
        value: prod.127.0.0.1.nip.io